### ISSUE TITLE
Change dedup program?

### ISSUE THREAD

**Issue by tamburinif** [bhattlab/bhattlab_workflows#11]
I wonder if we might be better off using super deduper https://ibest.github.io/HTStream/#hts_SuperDeduper since to my knowledge it produces synced paired-end files and having two syncing steps in our pipeline slows things a bit.

**Comment by jribado** [comment]
We initially chose to ignore it because it could not be added with conda, but if we are going with singularity may be a good idea.

**Comment by tamburinif** [comment]
Ah, makes sense. Good idea - we can add it back if someone ends up setting up singularity.

**Comment by elimoss** [comment]
Just noticed this.  I happen to have set up singularity for preprocessing.  This could be reverted back to super deduper if there's interest.

**Comment by tamburinif** [comment]
This would eliminate a syncing step if we deduplicate then trim, I believe? So I am in favor if that is accurate and if others agree

**Comment by bsiranosian** [comment]
I also think our sync solution should be changed to [fastq_pair] (https://github.com/linsalrob/fastq-pair) now that we're using singularity. It's order of magnitude faster than the python script - which has been taking >12h to run for me some times.
