### ISSUE TITLE
Test dataset and branching

### ISSUE THREAD

**Issue by bsiranosian** [bhattlab/bhattlab_workflows#12]
@tamburinif @elimoss @jribado We're getting to the point where this repo changes enough and is used enough that I think we need to keep a stable "master" branch and only change things on a dev branch. We should also come up with a standardized test dataset (could be automatically run through a continuous integration tool).

**Comment by elimoss** [comment]
i like this idea so damn much.  continuous integration is really the next level for automated testing. Getting it to happen for a bioinformatic workflow seems like it'd require thorough containerization.  maybe google cloud build would work?

fyi: https://github.com/marketplace/category/continuous-integration

**Comment by elimoss** [comment]
just to bump this--i'm currently containerizing, making continuous integration a real possibility.
