### ISSUE TITLE
Compatibility with single-end data

### ISSUE THREAD

**Issue by tamburinif** [bhattlab/bhattlab_workflows#13]
I'm not ambitious enough but we should think about making preprocessing work with single end data. Surprisingly, there's enough of it out there that it would come in handy.

**Comment by bsiranosian** [comment]
I think the best idea might be to make a second workflow for single-end data. Then the snakefile wouldn't get all clogged up with extra cases. Assembly and Kraken already can take in single or paired data. 

Maybe the next time someone has to process single-end data they can make it into a workflow?
