### ISSUE TITLE
shouldn't preprocessing use EXTENSION?

### ISSUE THREAD

**Issue by elimoss** [bhattlab/bhattlab_workflows#16]
in preprocessing/preprocessing.snakefile, line 17, the extensions used are hardcoded.  Shouldn't `tuple(['fastq.gz', 'fq.gz'])` be replaced with `EXTENSION` if this is going to be pulled from the config to begin with?  I encountered this by providing some *.fq files, specifying '.fq' as my extension, and still getting no result until I made this substitution.  Just making sure as I'm not too familiar with this code.

**Comment by bsiranosian** [comment]
Fixed in https://github.com/bhattlab/bhattlab_workflows/commit/bb656f6810482dbedb6596350522d6a165515dab
