### ISSUE TITLE
syncing script is not flexible with header formats

### ISSUE THREAD

**Issue by tamburinif** [bhattlab/bhattlab_workflows#19]
It appears that the syncing script cannot handle fastq headers that are not in standard illumination format and puts all reads into the orphans file. This commonly affects data downloaded from SRA, for example. We definitely need to fix this asap.

**Comment by tamburinif** [comment]
edit: this works for some SRA data but not all

**Comment by bsiranosian** [comment]
Can you post an example of headers where this fails? You could also adjust the regex on line 59 to match what your sra reads have.

**Comment by tamburinif** [comment]
It looks like any header that ends in /1 or /2 fails, which isn't great
eg: @HWUSI-EAS740_103031124:1:100:10000:11286/1

I made my own version of the script with adjusted regex which I can share if needed
