### ISSUE TITLE
Preprocessing_TrimGalore eroor

### ISSUE THREAD

**Issue by chrissev** [bhattlab/bhattlab_workflows#20]
**This was my command**:
snakemake --configfile ~/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/configpreprocessing.yaml -s ~/asbhatt/chris/tools/bhattlab_workflows/preprocessing/preprocessing.snakefile --profile scg --jobs 400

**Here is my .yaml file**:
# specify directories
raw_reads_directory: /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/L*
output_directory: /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2
read_specification: ['1', '2']
extension: .fastq.gz
# specify parameters for TrimGalore -- automatically chcecks the adaptor type
trim_galore:
  quality:  30
  start_trim: 15
  end_trim: 0
  min_read_length: 60
rm_host_reads:
  host_genome: /labs/asbhatt/data/host_reference_genomes/hg19/hg19.fa

**This was my output**:
Trying to restart job 184.
Error in rule trim_galore:
    jobid: 166
    output: /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_ICt103018_1_val_1.fq.gz, /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_ICt103018_2_val_2.fq.gz, /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_ICt103018_unpaired.fq.gz
    cluster_jobid: 8592599

Trying to restart job 166.
Error in rule trim_galore:
    jobid: 182
    output: /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_Zym103018_1_val_1.fq.gz, /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_Zym103018_2_val_2.fq.gz, /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_Zym103018_unpaired.fq.gz
    cluster_jobid: 8592582

Trying to restart job 182.
Error in rule trim_galore:
    jobid: 179
    output: /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_81_dn6_1_val_1.fq.gz, /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_81_dn6_2_val_2.fq.gz, /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/gutdecon2/gutdecon2_output/01_processing/01_trimmed/CS_81_dn6_unpaired.fq.gz
    cluster_jobid: 8592624

Trying to restart job 179.

**Comment by elimoss** [comment]
Could you post the contents of the file slurm-8592599.out please?

**Comment by elimoss** [comment]
also, your raw reads directory should be /labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/19-03-19_chris_gutdecon1/chris_demux/collapsed, and your extension should be .fq.gz

**Comment by elimoss** [comment]
This ended up being a problem related to collapsing data across samples and compressing, although the specific cause is still unknown.  closing because it's worked around, but let's keep an eye out..
