### ISSUE TITLE
Error in gplots library call in sourmash

### ISSUE THREAD

**Issue by alvinh315** [bhattlab/bhattlab_workflows#26]
Error in rule plot_R_k21:
    jobid: 214
    output: /oak/stanford/scg/lab_asbhatt/alvinhan/projects/hotmice_sourmash/sourmash/04_sourmash_compare/compare_k21_heatmap_complete.pdf

RuleException:
CalledProcessError in line 151 of /oak/stanford/scg/lab_asbhatt/alvinhan/projects/hotmice_sourmash/sourmash_tools/sourmash.snakefile:
Command 'set -euo pipefail;  Rscript --vanilla /oak/stanford/scg/lab_asbhatt/alvinhan/projects/hotmice_sourmash/.snakemake/scripts/tmpxg8sobsl.heatmaps.R' returned non-zero exit status 1.
  File "/oak/stanford/scg/lab_asbhatt/alvinhan/projects/hotmice_sourmash/sourmash_tools/sourmash.snakefile", line 151, in __rule_plot_R_k21
  File "/labs/asbhatt/alvinhan/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run

[Wed Feb  5 12:07:41 2020]
localrule plot_R_k51:
    input: /oak/stanford/scg/lab_asbhatt/alvinhan/projects/hotmice_sourmash/sourmash/04_sourmash_compare/compare_k51.csv
    output: /oak/stanford/scg/lab_asbhatt/alvinhan/projects/hotmice_sourmash/sourmash/04_sourmash_compare/compare_k51_heatmap_complete.pdf
    jobid: 216

Error in library(gplots) : there is no package called ‘gplots’
Execution halted

Doing things locally resolves this problem, not sure if this is just me being dumb.

**Comment by bsiranosian** [comment]
Fixed 0f4e7e3968ed05d78f1d614420d6d05ff1bf19ff
