### ISSUE TITLE
PreProcessing Workflow in SnakeMake

### ISSUE THREAD

**Issue by chrissev** [bhattlab/bhattlab_workflows#4]
**This was my command:**
(preprocessing) [02:34:19] hppsl230s-rcf-412-01-l:~/.config/snakemake > snakemake -np --configfile ~/asbhatt/chris/project/gutdecon/testpoop/testpoop1.yaml.txt -s ~/asbhatt/chris/tools/bhattlab_workflows/preprocessing/preprocessing.snakefile --profile scg 
/labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/3.links
['sample_2_R2.fastq.gz', 'sample_5_R1.fastq.gz', 'sample_10_R1.fastq.gz', 'sample_1_R1.fastq.gz', 'sample_8_R2.fastq.gz', 'sample_7_R1.fastq.gz', 'sample_UNKNOWN_R1.fastq.gz', 'sample_9_R2.fastq.gz', 'sample_UNKNOWN_R2.fastq.gz', 'sample_11_R2.fastq.gz', 'sample_13_R1.fastq.gz', 'sample_11_R1.fastq.gz', 'sample_9_R1.fastq.gz', 'sample_10_R2.fastq.gz', 'sample_6_R2.fastq.gz', 'sample_7_R2.fastq.gz', 'sample_1_R2.fastq.gz', 'sample_3_R1.fastq.gz', 'sample_8_R1.fastq.gz', 'sample_3_R2.fastq.gz', 'sample_6_R1.fastq.gz', 'sample_4_R1.fastq.gz', 'sample_12_R1.fastq.gz', 'sample_14_R2.fastq.gz', 'sample_4_R2.fastq.gz', 'sample_2_R1.fastq.gz', 'sample_5_R2.fastq.gz', 'sample_13_R2.fastq.gz', 'sample_12_R2.fastq.gz', 'sample_14_R1.fastq.gz']

**Here's my Output**
[Tue Nov  6 14:51:26 2018] Waiting at most 5 seconds for missing files.
[Tue Nov  6 14:51:31 2018] MissingOutputException in line 58 of /home/cseveryn/asbhatt/chris/tools/bhattlab_workflows/preprocessing/preprocessing.snakefile:
[Tue Nov  6 14:51:31 2018] Missing files after 5 seconds:
[Tue Nov  6 14:51:31 2018] /labs/asbhatt/chris/project/gutdecon/testpoop/testpoopoutput/qc/01_trimmed/sample_13_2_val_2.fq.gz
[Tue Nov  6 14:51:31 2018] /labs/asbhatt/chris/project/gutdecon/testpoop/testpoopoutput/qc/01_trimmed/sample_13_1_val_1.fq.gz
[Tue Nov  6 14:51:31 2018] This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
[Tue Nov  6 14:51:31 2018] Shutting down, this might take some time.
[Tue Nov  6 14:51:31 2018] Exiting because a job execution failed. Look above for error message
[Tue Nov  6 14:51:31 2018] Complete log: /home/cseveryn/.config/snakemake/.snakemake/log/2018-11-06T145030.120889.snakemake.log
/labs/asbhatt/chris/project/gutdecon/18-11-1_chris_gutdecon1/3.links
['sample_2_R2.fastq.gz', 'sample_5_R1.fastq.gz', 'sample_10_R1.fastq.gz', 'sample_1_R1.fastq.gz', 'sample_8_R2.fastq.gz', 'sample_7_R1.fastq.gz', 'sample_UNKNOWN_R1.fastq.gz', 'sample_9_R2.fastq.gz', 'sample_UNKNOWN_R2.fastq.gz', 'sample_11_R2.fastq.gz', 'sample_13_R1.fastq.gz', 'sample_11_R1.fastq.gz', 'sample_9_R1.fastq.gz', 'sample_10_R2.fastq.gz', 'sample_6_R2.fastq.gz', 'sample_7_R2.fastq.gz', 'sample_1_R2.fastq.gz', 'sample_3_R1.fastq.gz', 'sample_8_R1.fastq.gz', 'sample_3_R2.fastq.gz', 'sample_6_R1.fastq.gz', 'sample_4_R1.fastq.gz', 'sample_12_R1.fastq.gz', 'sample_14_R2.fastq.gz', 'sample_4_R2.fastq.gz', 'sample_2_R1.fastq.gz', 'sample_5_R2.fastq.gz', 'sample_13_R2.fastq.gz', 'sample_12_R2.fastq.gz', 'sample_14_R1.fastq.gz']

**Comment by jribado** [comment]
Corrected with remove extra "_[2]" in output file name that caused error. Files correctly produced put assigned to the wrong output name.
