### ISSUE TITLE
das_tool version needs to be added in the YAML file

### ISSUE THREAD

**Issue by Anqi-Dai** [bhattlab/bhattlab_workflows#46]
Hi developers, 
I recently am running the binning step using the `bin_das_tool_manysamp.snakefile`, and met a `bash: Fasta_to_Scaffolds2Bin.sh: command not found` error. 
It was because the dastool team recently (March 2022) released a version 1.1.4 and now there is not a `Fasta_to_Scaffolds2Bin.sh` anymore. 
So I would suggest to add `das_tool=1.1.3` in the `das_tool.yaml` file to make sure the `Fasta_to_Scaffolds2Bin.sh` still exists, and the pipeline can finish.

Regards.
Angel

**Comment by bsiranosian** [comment]
Thanks for the catch, updated in https://github.com/bhattlab/bhattlab_workflows/commit/19b78b1fb8f9e3b4f8a6bfd7483c448a47f72147
