### ISSUE TITLE
Lost sync.py script commit?

### ISSUE THREAD

**Issue by tamburinif** [bhattlab/bhattlab_workflows#7]
I can see that Ben updated the sync.py script and corresponding snakefile in Nov 2018, however the current version of the snakefile has a hardcoded script to Jessy's SCG account in the sync step. What happened here? Did someone push an outdated version?

**Comment by bsiranosian** [comment]
Fixed https://github.com/bhattlab/bhattlab_workflows/commit/17c7d1d52801f99f3942b734c831ea4d5014cbc7
